[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
GlobalOptimization = "25b58b08-a34a-4ec2-a22a-6e6adccd2f2d"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
